
insert into usr (first_name, middle_name, last_name, email) values
('Иван', 'Игровевич', 'Иванов', 'ivanov11@my.example.com'),
('Валерий', 'Петрович', 'Петров', 'petrov22@my.example.com'),
('Иван', 'Петрович', 'Сидоров', 'sidorov33@my.example.com'),
('Семен', 'Семенович', 'Алексеев', 'alekseev44@my.example.com'),
('Александр', 'Вячеславович', 'Савинцев', 'savintsev55@my.example.com'),
('Вячеслав', 'Александрович', 'Лев', 'lev353@my.example.com'),
('Денис', 'Константинович', 'Кузнецов', 'kuznrtsov232@my.example.com'),
('Влад', 'Иванович', 'Горбатенков', 'gorbanenkov22@my.example.com'),
('Игорь', 'Артемьевич', 'Богач', 'bogash132@my.example.com'),
('Илья', 'Семенович', 'Троекуров', 'troekurov5552v@my.example.com');