
insert into usr (first_name, middle_name, last_name, email) values
('Иван', 'Игровевич', 'Иванов', 'ivanov11@my.example.com'),
('Валерий', 'Петрович', 'Петров', 'petrov22@my.example.com'),
('Иван', 'Петрович', 'Сидоров', 'sidorov33@my.example.com'),
('Семен', 'Семенович', 'Алексеев', 'alekseev44@my.example.com'),
('Александр', 'Вячеславович', 'Савинцев', 'savintsev55@my.example.com'),
('Вячеслав', 'Александрович', 'Лев', 'lev353@my.example.com'),
('Денис', 'Константинович', 'Кузнецов', 'kuznrtsov232@my.example.com'),
('Влад', 'Иванович', 'Горбатенков', 'gorbanenkov22@my.example.com'),
('Игорь', 'Артемьевич', 'Богач', 'bogash132@my.example.com'),
('Илья', 'Семенович', 'Троекуров', 'troekurov5552v@my.example.com');

insert into usr (first_name, middle_name, last_name, e_mail,phone, birth_date,role_name,login,password) values
('Иван', 'Александрович', 'Иванов', 'iva5nov11@my.example.com','+797852555060','2003-01-01 00:00:00','user','rruu','12345'),
('Валерий', 'Петрович', 'Петров', 'petro1v22@my.example.com','+797852555060','2003-01-01 00:00:00','user','rruu','12345'),
('Иван', 'Игровевич', 'Сидоров', 'sidorov5323@my.example.com','+797852555060','2003-01-01 00:00:00','user','rruu','12345'),
('Иван', 'Игровевич', 'Алексеев', 'aleks5eev424@my.example.com','+797852555060','2003-01-01 00:00:00','user','rruu','12345'),
('Александр', 'Вячеславович', 'Савинцев', 'savi2ntsev55@my.example.com','+797852555060','2003-01-01 00:00:00','user','rruu','12345'),
('Вячеслав', 'Александрович', 'Лев', 'le5v353@my.example.com','+797852555060','2003-01-01 00:00:00','user','rruu','12345'),
('Иван', 'Игровевич', 'Кузнецов', 'kuz5nrt2sov232@my.example.com','+797852555060','2003-01-01 00:00:00','user','rruu','12345'),
('Влад', 'Иванович', 'Горбатенков', 'go5rb3anenkov22@my.example.com','+797852555060','2003-01-01 00:00:00','user','rruu','12345'),
('Игорь', 'Артемьевич', 'Богач', 'bogas5h2132@my.example.com','+797852555060','2003-01-01 00:00:00','user','rruu','12345'),
('Илья', 'Семенович', 'Троекуров', 'troe5k1urov5552v@my.example.com','+797852555060','2003-01-01 00:00:00','user','rruu','12345');